productly/productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
]

productly/productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'

urlpatterns = [
    path('', views.index, name='productos'),
    path(
        'formulario',
        views.formulario,
        name='formulario'
    ),
    path(
        '<int:producto_id>', 
        views.detalle, 
        name='detalle'
    ),
]

productly/productos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Categoria(models.Model):
    NOMBRE = models.CharField(max_length=255)

    def __str__(self):
        return self.NOMBRE

class Producto(models.Model):
    NOMBRE = models.CharField(max_length=255)
    STOCK = models.IntegerField()
    PUNTUACION = models.FloatField()
    ####  on_delete  #####
    # CASCADE: eliminar el producto
    # PROTECT: lanza un error
    # RESTRICT: elimina si no esxisten productos
    # SET_NULL: actualiza a valor nulo
    # SET_DEFAULT: asigna valor por defecto 
    CATEGORIA = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    FECHA_CREACION = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.NOMBRE

productly/productos/forms.py
from . import models
from django.forms import ModelForm


class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['NOMBRE', 'STOCK', 'PUNTUACION', 'CATEGORIA']

productly/productly/views.py
from django.shortcuts import render

def index(request):
    return render(
        request,
        "index.html",
    )

productly/productos/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ProductoForm
from .models import Producto
# Create your views here.

# /productos
def index(request):
    PRODUCTOS = Producto.objects.all()

    return render(
        request,
        'productos.html',
        context={'PRODUCTOS': PRODUCTOS}
    )

def detalle(request, producto_id):
    ### Este codigo se puede sustituir por el no comnetado ###
    # try:
    #     PRODUCTO = Producto.objects.get(id=producto_id)

    #     return render(
    #         request, 
    #         'detalle.html', 
    #         context={ 'PRODUCTO': PRODUCTO }
    #         )
    # except Producto.DoesNotExist:
    #     raise Http404()
    PRODUCTO = get_object_or_404(Producto, id=producto_id)

    return render(
        request,
        'detalle.html',
        context={'PRODUCTO': PRODUCTO}
    )

def formulario(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    else:
        form = ProductoForm()

    return render(
        request,
        'producto_form.html',
        {'form': form}
    )

productly/productos/templates/detalle.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h6>{{ PRODUCTO.NOMBRE }}</h6>
    <p>{{ PRODUCTO.CATEGORIA }}</p>
    <p>{{ PRODUCTO.STOCK }}</p>
    <p>{{ PRODUCTO.PUNTUACION }}</p>
    <p>{{ PRODUCTO.FECHA_CREACION }}</p>
</div>

{% endblock %}

productly/productos/templates/producto_form.html
{% extends 'base.html' %}

{% block content %}
<form novalidate action="{% url 'productos:formulario' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar" />
</form>
{% endblock %}

productly/productos/templates/productos.html
{% extends 'base.html' %}

{% block content %}

<h1>Productos</h1>

<a href="{% url 'productos:formulario' %}">Nuevo producto</a>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Puntuación</th>
            <th>Categoría</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in PRODUCTOS %}
        <tr>
            <td>
                <a href="{% url 'productos:detalle' producto.id %}">
                    {{ producto.NOMBRE }}
                </a>
            </td>
            <td>{{ producto.STOCK }}</td>
            <td>{{ producto.PUNTUACION }}</td>
            <td>{{ producto.CATEGORIA }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

productly/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:productos' %}">Productos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

productly/templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

productly/templates/django/forms/widgets/input.html
<input
    class="form-control {{ widget.attrs.class }}"
    type="{{ widget.type }}"
    name="{{ widget.name }}"
    {% if widget.value != None %}
        value="{{ widget.value|stringformat:'s' }}"
    {% endif %}
    {% include "django/forms/widgets/attrs.html" %}
>

productly/templates/django/forms/widgets/select.html
<select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %} class="form-select">{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
</select>

productly/templates/form_snippet.html
{% load add_attr %}

{% for field in form %}
  <div class="mb-3">
    {{ field.label_tag }}
    {% if field.errors %}
      {{ field | add_attr:'class:is-invalid' }}
    {% else %}
      {{ field }}
    {% endif %}
    <div class="invalid-feedback">
      {% for error in field.errors %}
        {{ error }}
      {% endfor %}
    </div>
  </div>
{% endfor %}

productly/templates/index.html
{% extends 'base.html' %}

{% block content %}
    Inicio APP
{% endblock %}